version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "gaohan085"
    versioning-strategy: increase
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Asia/Shanghai"
    groups:
      nodejs-dependencies:
        dependency-type: "production"
        patterns:
          - "@reduxjs/toolkit"
          - "axios"
          - "framer-motion"
          - "prop-types"
          - "react*"
          - "redux"
          - "swr"
      nodejs-development-dependencies:
        dependency-type: "development"
        patterns:
          - "@pmmmwh/react-refresh-webpack-plugin"
          - "@types/*"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "@webpack-cli/generators"
          - "css-loader"
          - "eslint"
          - "eslint-*"
          - "html-webpack-plugin"
          - "mini-css-extract-plugin"
          - "sass"
          - "sass-loader"
          - "style-loader"
          - "swc"
          - "swc-loader"
          - "typescript"
          - "webpack"
          - "webpack-cli"
          - "webpack-dev-server"
          - "@eslint/*"
          - "@stylistic/esling-plugin"
  - package-ecosystem: "gomod"
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Asia/Shanghai"
    directory: "/"
    reviewers:
      - "gaohan085"
    groups:
      golang-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "gorm.io/driver/postgres"
