version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "gaohan085"
    versioning-strategy: increase
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Asia/Shanghai"
    groups:
      nodejs-dependencies:
        dependency-type: "production"
        patterns:
          - "@reduxjs/toolkit"
          - "axios"
          - "prop-types"
          - "react*"
          - "redux"
          - "swr"
      nodejs-development-dependencies:
        dependency-type: "development"
        patterns:
          - "@eslint/compat"
          - "@eslint/eslintrc"
          - "@eslint/js"
          - "@pmmmwh/react-refresh-webpack-plugin"
          - "@stylistic/eslint-plugin"
          - "@types/eslint__js"
          - "@types/node"
          - "@types/react"
          - "@types/react-dom"
          - "@types/react-transition-group"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "@webpack-cli/generators"
          - "css-loader"
          - "css-minimizer-webpack-plugin"
          - "eslint"
          - "eslint-import-resolver-typescript"
          - "eslint-plugin-import-x"
          - "eslint-plugin-react"
          - "globals"
          - "html-webpack-plugin"
          - "mini-css-extract-plugin"
          - "sass"
          - "sass-loader"
          - "style-loader"
          - "swc"
          - "swc-loader"
          - "terser-webpack-plugin"
          - "ts-loader"
          - "typescript"
          - "typescript-eslint"
          - "webpack"
          - "webpack-cli"
          - "webpack-dev-server"
  - package-ecosystem: "gomod"
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Asia/Shanghai"
    directory: "/"
    reviewers:
      - "gaohan085"
    groups:
      golang-dependencies:
        patterns:
          - "*"
