version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "gaohan085"
    versioning-strategy: increase
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Asia/Shanghai"
    groups:
      nodejs-dependencies:
        dependency-type: "production && development"
        patterns:
          - "@reduxjs/toolkit"
          - "axios"
          - "prop-types"
          - "react*"
          - "redux"
          - "swr"
          - "motion"
          - "plyr"
          - "@tanstack/react-router"
          - "@tanstack/react-router-devtools"
          - "@eslint/compat"
          - "@eslint/eslintrc"
          - "@eslint/js"
          - "@stylistic/eslint-plugin"
          - "@types/eslint__js"
          - "@types/node"
          - "@types/react"
          - "@types/react-dom"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "@rsbuild/core"
          - "@rsbuild/plugin-react"
          - "@rsbuild/plugin-sass"
          - "eslint"
          - "eslint-import-resolver-typescript"
          - "eslint-plugin-import"
          - "eslint-plugin-react"
          - "eslint-plugin-react-refresh"
          - "globals"
          - "sass"
          - "typescript"
          - "typescript-eslint"
  - package-ecosystem: "gomod"
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Asia/Shanghai"
    directory: "/"
    reviewers:
      - "gaohan085"
    groups:
      golang-dependencies:
        patterns:
          - "*"
