/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ActressNameImport } from './routes/actress.$name'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ActressNameRoute = ActressNameImport.update({
  id: '/actress/$name',
  path: '/actress/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/actress/$name': {
      id: '/actress/$name'
      path: '/actress/$name'
      fullPath: '/actress/$name'
      preLoaderRoute: typeof ActressNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actress/$name': typeof ActressNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actress/$name': typeof ActressNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/actress/$name': typeof ActressNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/actress/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actress/$name'
  id: '__root__' | '/' | '/actress/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActressNameRoute: typeof ActressNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActressNameRoute: ActressNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/actress/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/actress/$name": {
      "filePath": "actress.$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
