name: Create Release On Push Tags

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: true

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action/setup@v4
        with:
          version: 10
          run_install: false
          
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: RsBuild
        run: pnpm build
        
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          pre_command: export CGO_ENABLED=1
          binary_name: videoserver
          ldflags: "-X 'go-fiber-react-ts/lib.Version=${{ github.ref_name }}' "
          compress_assets: OFF
          md5sum: FALSE
          sha256sum: TRUE
