# .github/workflows/go-release.yaml
name: Go Binary Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - name: Build
        run: pnpm build
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: videoServer
          ldflags: "-X 'go-fiber-react-ts/lib.Version=${{ github.ref_name }}"
          compress_assets: OFF
