#.github/workflows/release.yml

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-martix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 18.x ]
        goos: [linux, windows]
        goarch: [amd64]

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.43
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: make init && make build
