name: NodeJS with Vite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18 , 20 ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
          version: 8
          run_install: true

    - name: Build
      run: |
        npm install
        npx run build
